apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backend-tvu27
  namespace: nfs-tvu27
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi