apiVersion: v1
kind: Service
metadata:
  name: nfs-svc-tvu27
  namespace: nfs-tvu27
spec:
  type: ClusterIP
  selector:
    app: nfs-server-tvu27
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049

    - name: rpcbind
      port: 111
      protocol: TCP
      targetPort: 111

    - name: mountd
      port: 20048
      protocol: TCP
      targetPort: 20048